Added fp32, fp16 option for cpu with low mem
Akegarasu/ChatGLM-webui pull request #14
Opened 2023-03-19 01:08 UTC by haofanurusai

2023-03-19 15:25 UTC, Akegarasu requested changes

2023-03-19 15:25 UTC, Akegarasu commented on modules/model.py
> +        elif cmd_opts.precision == "fp16":
bf16

2023-03-19 15:25 UTC, Akegarasu commented on modules/model.py
> +            print("--precision ERROR: fp32 mode is only for CPU. Are you really ready to have such a large amount of vmem XD")
不需要报错，就直接按照参数加载

2023-03-19 15:27 UTC, Akegarasu commented
另外最好提交到dev，算了我自己改吧

2023-03-19 15:27 UTC, merged

2023-03-20 04:07 UTC, haofanurusai commented
好的 下次注意